#! /bin/bash

wget -O update.py https://raw.githubusercontent.com/chromium/chromium/main/tools/clang/scripts/update.py
CLANG_REVISION=$(cat update.py | grep CLANG_REVISION | head -n 1 | cut -d "'" -f 2)
CLANG_SUB_REVISION=$(cat update.py | grep CLANG_SUB_REVISION | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 2)
echo ${CLANG_REVISION}-${CLANG_SUB_REVISION}
rm -rf update.py
